/**
 * Shared payment types used across the payments module.
 */

export type PaymentProvider = 'toss' | 'stripe'

export type PaymentStatus =
  | 'pending'
  | 'ready'
  | 'in_progress'
  | 'done'
  | 'canceled'
  | 'failed'
  | 'expired'

export type PaymentMethod =
  | 'card'
  | 'transfer'
  | 'virtual_account'
  | 'phone'
  | 'gift_card'
  | 'easy_pay'

export interface PaymentRequest {
  /** Unique order ID generated by your application */
  orderId: string
  /** Amount in the smallest currency unit (e.g. KRW won, USD cents) */
  amount: number
  /** Currency code */
  currency: string
  /** Display name shown to the customer */
  orderName: string
  /** Customer email (optional) */
  customerEmail?: string
  /** Customer name (optional) */
  customerName?: string
  /** URL to redirect after successful payment */
  successUrl: string
  /** URL to redirect after failed/canceled payment */
  failUrl: string
  /** Additional metadata to attach to the payment */
  metadata?: Record<string, string>
}

export interface PaymentConfirmRequest {
  /** Payment key returned by the PG after customer approval */
  paymentKey: string
  /** Order ID that matches the original request */
  orderId: string
  /** Amount to confirm (must match original) */
  amount: number
}

export interface PaymentResult {
  provider: PaymentProvider
  paymentKey: string
  orderId: string
  amount: number
  currency: string
  status: PaymentStatus
  method?: PaymentMethod | string
  approvedAt?: string
  raw: unknown
}

export interface WebhookEvent {
  provider: PaymentProvider
  type: string
  paymentKey: string
  orderId: string
  status: PaymentStatus
  raw: unknown
}
