import { copySync, ensureDirSync, existsSync, readFileSync, writeFileSync } from 'fs-extra'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import {
  loadModuleManifest,
  getModuleSourceDir,
  resolveModuleDependencies,
  loadRegistry,
} from './registry.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

function findStartersPath(): string {
  const candidates = [
    resolve(__dirname, '../../../../starters'),
    resolve(__dirname, '../../../starters'),
    resolve(__dirname, '../../starters'),
    resolve(process.cwd(), 'starters'),
  ]

  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate
  }

  throw new Error('Could not locate starters directory.')
}

/**
 * Copy the base starter template into the target directory.
 */
export function copyBaseStarter(targetDir: string): void {
  const startersPath = findStartersPath()
  const basePath = resolve(startersPath, 'base')

  if (!existsSync(basePath)) {
    throw new Error(`Base starter not found at: ${basePath}`)
  }

  ensureDirSync(targetDir)
  copySync(basePath, targetDir, { overwrite: false, errorOnExist: false })
}

/**
 * Apply theme tokens by writing/merging the theme's CSS variables into the target.
 * Currently writes a reference to the chosen theme in a config file.
 */
export function applyTheme(targetDir: string, theme: string): void {
  const startersPath = findStartersPath()
  const tokensSrcPath = resolve(startersPath, 'tokens', `${theme}.css`)

  if (existsSync(tokensSrcPath)) {
    const targetTokensPath = resolve(targetDir, 'src', 'styles', 'tokens.css')
    ensureDirSync(dirname(targetTokensPath))
    copySync(tokensSrcPath, targetTokensPath, { overwrite: true })
  }

  // Write a factory.config.json to record which theme/preset was applied
  const configPath = resolve(targetDir, 'factory.config.json')
  const existing = existsSync(configPath)
    ? JSON.parse(readFileSync(configPath, 'utf-8'))
    : {}

  writeFileSync(
    configPath,
    JSON.stringify({ ...existing, theme }, null, 2) + '\n',
    'utf-8'
  )
}

/**
 * Apply a single module - copies source files to their target paths within targetDir.
 */
export function applyModule(targetDir: string, moduleName: string): void {
  const manifest = loadModuleManifest(moduleName)
  const moduleSourceDir = getModuleSourceDir(moduleName)

  for (const fileEntry of manifest.files) {
    const src = resolve(moduleSourceDir, fileEntry.source)
    const dest = resolve(targetDir, fileEntry.target)

    if (!existsSync(src)) {
      console.warn(`  [warn] Module file not found, skipping: ${src}`)
      continue
    }

    ensureDirSync(dirname(dest))
    copySync(src, dest, { overwrite: true })
  }
}

/**
 * Apply all modules for a given preset, resolving dependencies first.
 */
export function applyModules(targetDir: string, moduleNames: string[]): void {
  const registry = loadRegistry()
  const resolved = resolveModuleDependencies(moduleNames, registry)

  for (const moduleName of resolved) {
    // Only apply modules that have a module.json (skip ones not yet implemented)
    try {
      applyModule(targetDir, moduleName)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      // If module manifest is missing, warn but continue
      if (message.includes('ENOENT') || message.includes('not found')) {
        console.warn(`  [warn] Module "${moduleName}" files not found in registry, skipping.`)
      } else {
        throw err
      }
    }
  }
}

/**
 * Scaffold a .env.local file with required env vars for the selected modules.
 */
export function scaffoldEnvFile(targetDir: string, moduleNames: string[]): void {
  const registry = loadRegistry()
  const resolved = resolveModuleDependencies(moduleNames, registry)

  const allEnvVars = new Set<string>()

  for (const moduleName of resolved) {
    try {
      const manifest = loadModuleManifest(moduleName)
      for (const envVar of manifest.envVars) {
        allEnvVars.add(envVar)
      }
    } catch {
      // skip modules without manifests
    }
  }

  if (allEnvVars.size === 0) return

  const envPath = resolve(targetDir, '.env.local')
  const lines = ['# Generated by Coding Factory CLI', '# Fill in the values below', '']

  for (const envVar of allEnvVars) {
    lines.push(`${envVar}=`)
  }

  lines.push('')
  writeFileSync(envPath, lines.join('\n'), 'utf-8')
}

/**
 * Update factory.config.json with metadata about the project setup.
 */
export function writeFactoryConfig(
  targetDir: string,
  config: {
    preset: string
    theme: string
    modules: string[]
    layout: string
  }
): void {
  const configPath = resolve(targetDir, 'factory.config.json')
  writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf-8')
}

export interface FactoryConfig {
  preset: string
  theme: string
  modules: string[]
  layout: string
}

/**
 * Read factory.config.json from an existing project directory.
 * Returns null if the file does not exist.
 */
export function readFactoryConfig(targetDir: string): FactoryConfig | null {
  const configPath = resolve(targetDir, 'factory.config.json')
  if (!existsSync(configPath)) return null
  return JSON.parse(readFileSync(configPath, 'utf-8')) as FactoryConfig
}

/**
 * Update the modules list in factory.config.json, adding newly installed modules.
 */
export function updateFactoryConfigModules(targetDir: string, addedModules: string[]): void {
  const configPath = resolve(targetDir, 'factory.config.json')
  const existing = existsSync(configPath)
    ? (JSON.parse(readFileSync(configPath, 'utf-8')) as FactoryConfig)
    : { preset: 'custom', theme: 'default', modules: [], layout: 'marketing' }

  const merged = Array.from(new Set([...existing.modules, ...addedModules]))
  writeFileSync(configPath, JSON.stringify({ ...existing, modules: merged }, null, 2) + '\n', 'utf-8')
}

/**
 * Merge dependencies from a module manifest into an existing package.json.
 * Skips if package.json does not exist.
 */
export function mergeDepsToPackageJson(
  targetDir: string,
  deps: Record<string, string>,
  devDeps: Record<string, string>
): void {
  const pkgPath = resolve(targetDir, 'package.json')
  if (!existsSync(pkgPath)) return

  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as Record<string, unknown>

  if (Object.keys(deps).length > 0) {
    pkg.dependencies = { ...(pkg.dependencies as Record<string, string> | undefined ?? {}), ...deps }
  }

  if (Object.keys(devDeps).length > 0) {
    pkg.devDependencies = { ...(pkg.devDependencies as Record<string, string> | undefined ?? {}), ...devDeps }
  }

  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8')
}

/**
 * Append env vars from a module to .env.example (not .env.local) in the target project.
 * Only adds vars that are not already present.
 */
export function appendEnvVars(targetDir: string, envVars: string[]): void {
  if (envVars.length === 0) return

  const envPath = resolve(targetDir, '.env.example')
  const existing = existsSync(envPath) ? readFileSync(envPath, 'utf-8') : ''

  const toAdd = envVars.filter((v) => !existing.includes(v))
  if (toAdd.length === 0) return

  const lines = existing.endsWith('\n') ? [] : ['\n']
  lines.push('# Added by factory add', ...toAdd.map((v) => `${v}=`), '')

  writeFileSync(envPath, existing + lines.join('\n'), 'utf-8')
}
